spring.application.name=uniplanner

spring.datasource.url=jdbc:postgresql://localhost:5432/uniplanner
spring.datasource.username=postgres
spring.datasource.password=Aggtcraft1
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.example.uniplanner=DEBUG
logging.level.org.springframework.web=DEBUG
spring.web.resources.add-mappings=true