-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS academico.horarios
(
    id_horario integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_materia integer,
    dia character varying(20) COLLATE pg_catalog."default",
    hora_inicio time(6) without time zone,
    hora_final time(6) without time zone,
    CONSTRAINT horarios_pkey PRIMARY KEY (id_horario)
    );

CREATE TABLE IF NOT EXISTS academico.materias
(
    id_materia integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_usuario integer,
    nombre character varying(40) COLLATE pg_catalog."default",
    color character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT materias_pkey PRIMARY KEY (id_materia)
    );

CREATE TABLE IF NOT EXISTS catalogo.prioridad
(
    id_prioridad integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT prioridad_pkey PRIMARY KEY (id_prioridad)
    );

CREATE TABLE IF NOT EXISTS catalogo.roles
(
    id_rol integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id_rol)
    );

CREATE TABLE IF NOT EXISTS operaciones.recordatorios
(
    id_recordatorio integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_tarea integer,
    horas_antes integer,
    fecha_recordatorio date,
    enviado bit(1),
    CONSTRAINT recordatorios_pkey PRIMARY KEY (id_recordatorio)
    );

CREATE TABLE IF NOT EXISTS operaciones.tareas
(
    id_tarea integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_materia integer,
    titulo character varying(100) COLLATE pg_catalog."default",
    descripcion character varying(200) COLLATE pg_catalog."default",
    fecha_creacion date,
    fecha_entrega date,
    id_prioridad integer,
    estatus character varying(25) COLLATE pg_catalog."default",
    id_usuario integer,
    fecha_entregada date,
    CONSTRAINT tareas_pkey PRIMARY KEY (id_tarea)
    );

CREATE TABLE IF NOT EXISTS seguridad.preguntas
(
    id_pregunta integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_usuario integer,
    pregunta1 character varying(100) COLLATE pg_catalog."default",
    pregunta2 character varying(100) COLLATE pg_catalog."default",
    pregunta3 character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT preguntas_pkey PRIMARY KEY (id_pregunta)
    );

CREATE TABLE IF NOT EXISTS seguridad.usuarios
(
    id_usuario integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(255) COLLATE pg_catalog."default",
    apellidos character varying(255) COLLATE pg_catalog."default",
    correo character varying(255) COLLATE pg_catalog."default",
    password_hash character varying(100) COLLATE pg_catalog."default",
    id_rol integer,
    fecha_alta date,
    fecha_modificacion date,
    estado character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario)
    );

ALTER TABLE IF EXISTS academico.horarios
    ADD CONSTRAINT horarios_id_materia_fkey FOREIGN KEY (id_materia)
    REFERENCES academico.materias (id_materia) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS academico.materias
    ADD CONSTRAINT id_usuario FOREIGN KEY (id_usuario)
    REFERENCES seguridad.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS operaciones.recordatorios
    ADD CONSTRAINT "idTarea" FOREIGN KEY (id_tarea)
    REFERENCES operaciones.tareas (id_tarea) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS operaciones.tareas
    ADD CONSTRAINT id_materia FOREIGN KEY (id_materia)
    REFERENCES academico.materias (id_materia) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS operaciones.tareas
    ADD CONSTRAINT id_prioridad FOREIGN KEY (id_prioridad)
    REFERENCES catalogo.prioridad (id_prioridad) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS operaciones.tareas
    ADD CONSTRAINT tareas_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES seguridad.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS seguridad.preguntas
    ADD CONSTRAINT id_usuario FOREIGN KEY (id_usuario)
    REFERENCES seguridad.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS seguridad.usuarios
    ADD CONSTRAINT "idRol" FOREIGN KEY (id_rol)
    REFERENCES catalogo.roles (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;